name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=20.3.3
  - mlflow=2.2.2
  - scikit-learn=1.2.1
  - matplotlib=3.7.1
  - pillow=9.4.0
  - pip:
      - wandb==0.13.11
